# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(default='', max_length=55)),
                ('bank', models.CharField(default='', max_length=55)),
                ('bank_code', models.CharField(blank=True, max_length=4)),
                ('acc_no', models.CharField(blank=True, max_length=10)),
                ('created', models.DateTimeField()),
                ('recipient_code', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('mode', models.NullBooleanField()),
                ('interval', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=0)),
                ('freq_factor', models.IntegerField(default=0)),
                ('pay_value', models.IntegerField(default=0)),
                ('pay_qty', models.IntegerField(default=0)),
                ('pay_count', models.IntegerField(default=0)),
                ('next_date', models.DateField()),
                ('final_date', models.DateField(blank=True)),
                ('budget_status', models.IntegerField(default=0)),
                ('pay_ref', models.CharField(max_length=30, null=True)),
                ('pay_status', models.CharField(max_length=10, null=True)),
                ('amount_funded', models.IntegerField(null=True)),
                ('recipient_code', models.CharField(max_length=20)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chris.Bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_4', models.CharField(default='0000', max_length=4)),
                ('auth', models.CharField(blank=True, max_length=20)),
                ('card_scheme', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=32)),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
