# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='auth',
            new_name='auth_code',
        ),
    ]
