# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0037_auto_20190908_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='acc_no',
            field=models.IntegerField(blank=True),
        ),
    ]
