# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0038_auto_20190908_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='acc_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
